spring.application.name=warehouseMS
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/wms_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:admin@123}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# QR Code Configuration
qrcode.output.dir=qrcodes